### PR TITLE
Adds exports and updates type definitions for MeshoptSimplifier

### PR DESCRIPTION
**Pull request by donmccurdy**
Changes:

- Adds missing exports for MeshoptSimplifier
- Fixes typo in TypeScript type declarations
- Changes `[Flags]` to `Flags[]`, allowing empty array

### CODE REVIEW

**Comment by zeux** [comment]
Thanks! I completely forgot about `index.js` :D I can republish this as 0.18.1.

**Comment by zeux** [comment]
Actually, would you mind changing the version number in js/package.json to 0.18.1? Then I'd be able to simply publish the npm package generated by GHA.

**Comment by donmccurdy** [comment]
Done! 👍🏻

**Comment by zeux** [comment]
Thanks! Published https://www.npmjs.com/package/meshoptimizer

**Pull request merged**
